/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SgAvatar {
        "avatar": string;
        "background": string;
        "color": string;
        "datasrc": string;
        "femaleImage": string;
        "fontSize": number;
        "length": number;
        "maleImage": string;
        "name": string;
        "rounded": boolean;
        "sex": string;
        "size": number;
    }
}
declare global {
    interface HTMLSgAvatarElement extends Components.SgAvatar, HTMLStencilElement {
    }
    var HTMLSgAvatarElement: {
        prototype: HTMLSgAvatarElement;
        new (): HTMLSgAvatarElement;
    };
    interface HTMLElementTagNameMap {
        "sg-avatar": HTMLSgAvatarElement;
    }
}
declare namespace LocalJSX {
    interface SgAvatar {
        "avatar"?: string;
        "background"?: string;
        "color"?: string;
        "datasrc"?: string;
        "femaleImage"?: string;
        "fontSize"?: number;
        "length"?: number;
        "maleImage"?: string;
        "name"?: string;
        "rounded"?: boolean;
        "sex"?: string;
        "size"?: number;
    }
    interface IntrinsicElements {
        "sg-avatar": SgAvatar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sg-avatar": LocalJSX.SgAvatar & JSXBase.HTMLAttributes<HTMLSgAvatarElement>;
        }
    }
}
